### ISSUE TITLE
点击【transpose(switch row/column)】按钮 报错

### ISSUE THREAD

**Issue by xiweicheng** [mengshukeji/chartMix#6]
![image](https://user-images.githubusercontent.com/9198971/134006861-a72aab93-bb23-4e49-a92c-e22bd9df8c49.png)

**Comment by xiweicheng** [comment]
通过这个demo可以复现：https://mengshukeji.github.io/LuckysheetDemo/

**Comment by Naeemo** [comment]
I have this issue too

**Comment by Naeemo** [comment]
@xiweicheng try `npm run lib` locally on master branch. The bug was fixed already, just nobody update the luckysheet embeded one.

**Comment by Ma-XiaoFei** [comment]
现在好像还有这个问题呀 @xiweicheng
